name: exiftool-binderized
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyterlab>=1.0
  - perl-image-exiftool
  - pandas-datareader>=0.5.0
  - matplotlib>=2.1.1
  - seaborn
  - regex
